### ISSUE TITLE
Multiple AWS account support 

### ISSUE THREAD

**Issue by bboonen** [mlabouardy/komiser#67]
Hi,

Can you tell me if you already support multiple AWS account via cross-account roles?
thanks!

**Comment by mlabouardy** [comment]
@bboonen @lesaff by the way I have released the support of GCP if you guys are interested

**Comment by bboonen** [comment]
@mlabouardy Can you explain how to add multiple AWS accounts? I've pulled the new docker image but I can't seem to find where to configure it.

**Comment by dimisjim** [comment]
@bboonen Indeed, there doesn't seem to be support for this yet for AWS.

@mlabouardy  Any plans on adding it?

**Comment by kevinrook** [comment]
@mlabouardy so has the Multiple AWS accounts feature been added yet?

**Comment by dimisjim** [comment]
@mlabouardy Could we reopen this issue, as it's not fixed yet?

**Comment by mlabouardy** [comment]
@dimisjim  sure, multiple AWS account support will be released today (promise :) ) @bboonen @kevinrook sorry for late response

**Comment by mlabouardy** [comment]
@dimisjim @kevinrook @bboonen @lesaff multiple AWS accounts is now supported https://github.com/mlabouardy/komiser/releases/tag/2.2.0 🥇

**Comment by bboonen** [comment]
Perfect @mlabouardy ! Thanks. 
Now that multiple AWS accounts work, can you also aggregate the billing overview for all the accounts? And if you then click on them get the detailed billing per account?

**Comment by mlabouardy** [comment]
@bboonen yes I'm working on that + filtering resources by tags :)
